server:
  port: 5000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true    
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: hr
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    view-names: th/*

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      #JPA가 사용하는 기본 넘버링 전략을 사용하지 않는다.
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: false

  jackson:
    serialization:
      fail-on-empty-beans: false
      
  servlet:
    multipart:
      enabled: true
      location: C:/images/
      max-file-size: 10MB
      max-request-size: 50MB
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: tv9579@gmail.com
    password: htqtsmetmkzzizyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true 
cos:
  key: cosKey
